### ISSUE TITLE
Could you please show how all functions work in main()?

### ISSUE THREAD

**Issue by Denys-Bredun** [oschonrock/cproj#1]

**Comment by oschonrock** [comment]
Please have a look at the test suite:

tests/test_hashtable.c

and the demo app / becnhmark:

apps/topwords.c

They demonstrate the full capabilities.

**Comment by DenisBredun** [comment]
@oschonrock , okie, thanks!

**Comment by oschonrock** [comment]
closing.. come back with questions if you wish
